# Generated by Django 5.1.4 on 2025-04-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
