# Generated by Django 5.1.4 on 2025-04-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('accessory', 'Accessory'), ('charger', 'Charger')], default='accessory', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='storages',
            field=models.JSONField(default=list),
        ),
    ]
