# Generated by Django 5.1.4 on 2025-04-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('Cash On Delivery', 'Cash On Delivery')], default='Cash On Delivery', max_length=20),
        ),
    ]
